version: '3'
services:
  db:
    image: postgres
    ports:
      - "3457:5432"
    environment:
      - POSTGRES_USER=hackathonsdv53
      - POSTGRES_PASSWORD=muZ1X4#19VwqF!n4
      - POSTGRES_DB=djclimat
  nginx:
    image: nginx
    ports:
      - "8080:80"
    environment:
     - NGINX_HOST=djclimat.sdv.fr
     - NGINX_PORT=80
    volumes:
      - ./templates:/etc/nginx/templates

#  node:
#    build:
#      context: .
#      dockerfile: Dockerfile.node
#    restart: always
#    ports:
#      - 3000:3000
#    volumes:
#      - ./node_app:/app


